baseurl: ""
url: "https://hacktival.io"
title: Hacktival Hackathon
description: >-
  Welcome to the largest student-run hackathon in Germany!
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM
lang: en_US
image: /assets/images/htv_cover_image.jpg
logo: /assets/images/htv_cover_image.jpg

slogan: Rethink Hackathon
info_email: info@hackundsoehne.de
date: May 11th and 12th, 2019
apply_url: https://apply.hacktival.io/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  about:
    output: true
  juries:
    output: true
  faq:
    output: true

sass:
  style: compressed

exclude: ["README.md", "Dockerfile"]