baseurl: ""
url: "https://hacktival.io"
title: Hacktival Hackathon
description: >-
  The Hacktival Hackathon 2019 is the largest student-run hackathon in Germany. Happening May 11th and 12th, apply now!
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM
lang: en_US
image: /assets/images/htv_cover_image.jpg
logo: /assets/images/htv_cover_image.jpg

slogan: Rethink Hackathon
info_email: info@hackundsoehne.de
date: May 11th and 12th, 2019
apply_url: https://apply.hacktival.io/
deadline: "May 5, 2019 23:59:59 GMT+02:00"
deadline_title: "Application Deadline:"
deadline_expired: "The application deadline expired."

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  about:
    output: true
  juries:
    output: true
  faq:
    output: true
  cats:
    output: true

sass:
  style: compressed

exclude: ["README.md", "Dockerfile"]
