baseurl: ""
url: "https://hacktival.io"
description: >-
  Welcome to the largest student-run hackathon in Germany!
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM
lang: en_US
image: https://hacktival.io/fb-cover.jpg

slogan: Rethink Hackthon
info_email: info@hackundsoehne.de
date: May 11th and 12th, 2019
apply_url: https://apply.hacktival.io/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  about:
    output: true
  juries:
    output: true
  faq:
    output: true

exclude: ["README.md"]